// Tracker
export const GET_TRACKER_INF0 = "GET_TRACKER_INF0 "
export const GET_SINGLE_TRACKER_INFO = "GET_SINGLE_TRACKER_INFO"
export const CREATE_TRACKER_INF0 = "CREATE_TRACKER_INF0"
export const DELETE_TRACKER_INF0 = "DELETE_TRACKER_INF0"
export const UPDATE_TRACKER_INF0 = "UPDATE_TRACKER_INF0"
export const UPDATE_TRACKER_STATE = "UPDATE_TRACKER_STATE"
export const SORTED_DATA = "SORTED_DATA"
export const SEARCHED_DATA = "SEARCHED_DATA"
export const RANGED_DATA = "RANGED_DATA"
export const TYPED_DATA = "TYPED_DATA"
export const CATEGORY_DATA = "CATEGORY_DATA"
// Modal
export const UPDATE_MODAL_STATE = "UPDATE_MODAL_STATE"
